// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace tipo.Migrations
{
    [DbContext(typeof(tipoContext))]
    [Migration("20190802160950_total")]
    partial class total
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tipo.Models.Acudiente", b =>
                {
                    b.Property<int>("AcudienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Telefono");

                    b.HasKey("AcudienteID");

                    b.ToTable("Acudiente");
                });

            modelBuilder.Entity("tipo.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcudienteID");

                    b.Property<string>("Apellido");

                    b.Property<string>("Nombre");

                    b.Property<DateTime>("edad");

                    b.HasKey("EstudianteID");

                    b.HasIndex("AcudienteID");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("tipo.Models.Juego", b =>
                {
                    b.Property<int>("JuegoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nivel");

                    b.Property<string>("puntuacion");

                    b.HasKey("JuegoID");

                    b.ToTable("Juego");
                });

            modelBuilder.Entity("tipo.Models.Estudiante", b =>
                {
                    b.HasOne("tipo.Models.Acudiente", "Acudiente")
                        .WithMany()
                        .HasForeignKey("AcudienteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
